# Generated by Django 5.2.13 on 2026-04-26 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_table", models.IntegerField()),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("type_de_client", models.CharField(max_length=50)),
                ("table_capacite", models.IntegerField()),
                ("table_statut", models.CharField(max_length=50)),
                ("commentaire", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("unite_de_mesure", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("categorie", models.CharField(max_length=100)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("duree_cuisson", models.CharField(max_length=50)),
                ("nombre_personnes", models.IntegerField()),
                (
                    "quantite_utilisee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Restaurant.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_table", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("statut", models.CharField(max_length=50)),
                (
                    "montant_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("mode_paiement", models.CharField(max_length=50)),
                ("mode_livraison", models.CharField(max_length=50)),
                (
                    "adresse_livraison",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.client",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.produit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_table", models.IntegerField()),
                ("date", models.DateField()),
                ("heure", models.TimeField()),
                ("nombre_personnes", models.IntegerField()),
                ("statut", models.CharField(max_length=50)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.client",
                    ),
                ),
            ],
        ),
    ]
