# Generated by Django 5.2.13 on 2026-04-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id_employe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_emp', models.CharField(max_length=100)),
                ('role', models.CharField(default='Serveur', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=100)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id_table', models.AutoField(primary_key=True, serialize=False)),
                ('numero_table', models.IntegerField(unique=True)),
                ('nb_places', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('type_commande', models.CharField(choices=[('SUR_PLACE', 'Sur place'), ('LIVRAISON', 'Livraison')], default='SUR_PLACE', max_length=20)),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.employe')),
                ('id_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant.table')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Restaurant.commande')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.produit')),
            ],
        ),
    ]
