# Generated by Django 5.2.13 on 2026-06-08 01:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id_Client", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(blank=True, default="", max_length=20)),
                ("Prenom", models.CharField(blank=True, default="", max_length=20)),
                (
                    "Tel",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        blank=True, max_length=45, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "Type_de_Client",
                    models.CharField(
                        choices=[
                            ("Particulier", "Particulier"),
                            ("Entreprise", "Entreprise"),
                        ],
                        default="Particulier",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "Client",
            },
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                ("id_Employe", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=20, verbose_name="Nom")),
                ("Prenom", models.CharField(max_length=20, verbose_name="Prénom")),
                (
                    "Tel",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "Salaire",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salaire (FCFA)",
                    ),
                ),
                (
                    "Date_Embauche",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'embauche"
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "db_table": "Employe",
                "ordering": ["Nom", "Prenom"],
            },
        ),
        migrations.CreateModel(
            name="Equipement",
            fields=[
                ("id_Equipement", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=45)),
                (
                    "Etat",
                    models.CharField(
                        choices=[
                            ("Fonctionnel", "Fonctionnel"),
                            ("En panne", "En panne"),
                            ("En maintenance", "En maintenance"),
                            ("Hors service", "Hors service"),
                        ],
                        default="Fonctionnel",
                        max_length=45,
                    ),
                ),
                ("Date_Achat", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Équipement",
                "verbose_name_plural": "Équipements",
                "db_table": "Equipement",
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                ("id_Facture", models.AutoField(primary_key=True, serialize=False)),
                ("Date", models.DateField()),
                ("Montant", models.IntegerField()),
                ("Type", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "db_table": "Facture",
                "ordering": ["-Date"],
            },
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                ("id_Fournisseur", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=45, verbose_name="Nom")),
                ("Tel", models.CharField(blank=True, max_length=15, null=True)),
                ("Adresse", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "db_table": "Fournisseur",
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("id_Ingredient", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=45, verbose_name="Nom")),
                (
                    "Unite_de_Mesure",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Unité de mesure",
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Type"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrédient",
                "verbose_name_plural": "Ingrédients",
                "db_table": "Ingredient",
                "ordering": ["Nom"],
            },
        ),
        migrations.CreateModel(
            name="Poste",
            fields=[
                ("id_Poste", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Libelle_Poste",
                    models.CharField(max_length=45, verbose_name="Libellé du poste"),
                ),
            ],
            options={
                "verbose_name": "Poste",
                "verbose_name_plural": "Postes",
                "db_table": "Poste",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id_Table", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Numero_Table",
                    models.CharField(max_length=3, unique=True, verbose_name="Numéro"),
                ),
                (
                    "Capacite",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Capacité",
                    ),
                ),
                (
                    "Commentaire",
                    models.TextField(blank=True, null=True, verbose_name="Commentaire"),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "db_table": "Table",
                "ordering": ["Numero_Table"],
            },
        ),
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                ("id_Vehicule", models.AutoField(primary_key=True, serialize=False)),
                ("Immatriculation", models.CharField(max_length=15)),
                ("Modele", models.CharField(blank=True, max_length=20, null=True)),
                ("Marque", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Véhicule",
                "verbose_name_plural": "Véhicules",
                "db_table": "Vehicule",
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                ("id_Commande", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Date"
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("Sur place", "Sur place"),
                            ("À livrer", "À livrer"),
                            ("À emporter", "À emporter"),
                        ],
                        default="Sur place",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "Montant_Total",
                    models.IntegerField(default=0, verbose_name="Montant total (FCFA)"),
                ),
                (
                    "Mode_de_Paiement",
                    models.CharField(
                        choices=[
                            ("Espèces", "Espèces"),
                            ("Orange Money", "Orange Money"),
                            ("MTN MoMo", "MTN MoMo"),
                            ("Carte Bancaire", "Carte Bancaire"),
                        ],
                        default="Espèces",
                        max_length=45,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "Statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("prête", "Prête"),
                            ("livrée", "Livrée / Servie"),
                            ("annulée", "Annulée"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "id_Client",
                    models.ForeignKey(
                        db_column="id_Client",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "prise_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Prise par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "db_table": "Commande",
                "ordering": ["-Date"],
            },
        ),
        migrations.CreateModel(
            name="Deplacement",
            fields=[
                ("id_Deplacement", models.AutoField(primary_key=True, serialize=False)),
                ("Date_depart", models.DateTimeField(verbose_name="Date de départ")),
                ("Destination", models.TextField(blank=True, null=True)),
                (
                    "Distance_totale",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "id_Chauffeur",
                    models.ForeignKey(
                        db_column="id_Chauffeur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Restaurant.employe",
                        verbose_name="Chauffeur",
                    ),
                ),
                (
                    "id_Vehicule",
                    models.ForeignKey(
                        db_column="id_Vehicule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Restaurant.vehicule",
                        verbose_name="Véhicule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Déplacement",
                "verbose_name_plural": "Déplacements",
                "db_table": "Deplacement",
            },
        ),
        migrations.CreateModel(
            name="Action_Marketing",
            fields=[
                ("id_Action", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Type_Action",
                    models.CharField(max_length=20, verbose_name="Type d'action"),
                ),
                ("Description", models.TextField(blank=True, null=True)),
                ("Date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "Date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "Budget",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Budget (FCFA)"
                    ),
                ),
                (
                    "id_Responsable",
                    models.ForeignKey(
                        db_column="id_Responsable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Restaurant.employe",
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Marketing",
                "verbose_name_plural": "Actions Marketing",
                "db_table": "Action_Marketing",
                "ordering": ["-Date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id_Ingredient",
                    models.OneToOneField(
                        db_column="id_Ingredient",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="Restaurant.ingredient",
                        verbose_name="Ingrédient",
                    ),
                ),
                (
                    "Quantite_Actuelle",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Quantité actuelle",
                    ),
                ),
                (
                    "Seuil_Alerte",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Seuil d'alerte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "db_table": "Stock",
            },
        ),
        migrations.CreateModel(
            name="Approvisionnement",
            fields=[
                (
                    "id_Approvisionnement",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Date", models.DateField(verbose_name="Date")),
                (
                    "Quantite",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantité"
                    ),
                ),
                (
                    "Prix_Unitaire",
                    models.IntegerField(verbose_name="Prix unitaire (FCFA)"),
                ),
                (
                    "id_Deplacement",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_Deplacement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Restaurant.deplacement",
                    ),
                ),
                (
                    "id_Fournisseur",
                    models.ForeignKey(
                        db_column="id_Fournisseur",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "id_Ingredient",
                    models.ForeignKey(
                        db_column="id_Ingredient",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.ingredient",
                        verbose_name="Ingrédient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approvisionnement",
                "verbose_name_plural": "Approvisionnements",
                "db_table": "Approvisionnement",
                "ordering": ["-Date"],
            },
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                ("id_Livraison", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_Commande",
                    models.OneToOneField(
                        db_column="id_Commande",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.commande",
                        verbose_name="Commande",
                    ),
                ),
                (
                    "id_Deplacement",
                    models.ForeignKey(
                        db_column="id_Deplacement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Restaurant.deplacement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison",
                "verbose_name_plural": "Livraisons",
                "db_table": "Livraison",
            },
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                ("id_Maintenance", models.AutoField(primary_key=True, serialize=False)),
                ("Date", models.DateField()),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("Corrective", "Corrective"),
                            ("Préventive", "Préventive"),
                        ],
                        max_length=45,
                    ),
                ),
                ("Commentaire", models.TextField(blank=True, null=True)),
                (
                    "id_Equipement",
                    models.ForeignKey(
                        db_column="id_Equipement",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.equipement",
                        verbose_name="Équipement",
                    ),
                ),
                (
                    "id_Technicien",
                    models.ForeignKey(
                        db_column="id_Technicien",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Restaurant.employe",
                        verbose_name="Technicien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance",
                "verbose_name_plural": "Maintenances",
                "db_table": "Maintenance",
                "ordering": ["-Date"],
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                ("id_Produit", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=30, verbose_name="Nom du plat")),
                (
                    "Description",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Plat", "Plat principal"),
                            ("Entrée", "Entrée"),
                            ("Dessert", "Dessert"),
                            ("Boisson", "Boisson"),
                            ("Autre", "Autre"),
                        ],
                        max_length=45,
                        null=True,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "Duree_Cuisson",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Durée de cuisson",
                    ),
                ),
                (
                    "Nombre_Personnes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nombre de personnes"
                    ),
                ),
                (
                    "Prix",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix (FCFA)",
                    ),
                ),
                (
                    "Disponible",
                    models.BooleanField(
                        default=True, verbose_name="Disponible au menu"
                    ),
                ),
                (
                    "id_Createur",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_Createur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Restaurant.employe",
                        verbose_name="Chef en charge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit / Plat",
                "verbose_name_plural": "Produits / Plats",
                "db_table": "Produit",
                "ordering": ["Description", "Nom"],
            },
        ),
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("administrateur", "Administrateur"),
                            ("directeur", "Directeur"),
                            ("chef_cuisinier", "Chef Cuisinier"),
                            ("cuisinier", "Cuisinier"),
                            ("serveur", "Serveur"),
                            ("gestionnaire_stock", "Gestionnaire de Stock"),
                        ],
                        default="serveur",
                        max_length=30,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=15)),
                (
                    "employe",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Restaurant.employe",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id_Reservation", models.AutoField(primary_key=True, serialize=False)),
                ("Date", models.DateField(verbose_name="Date")),
                ("Heure", models.TimeField(verbose_name="Heure")),
                (
                    "Statut",
                    models.CharField(
                        choices=[
                            ("Confirmée", "Confirmée"),
                            ("Annulée", "Annulée"),
                            ("En attente", "En attente"),
                        ],
                        default="En attente",
                        max_length=45,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "id_Client",
                    models.ForeignKey(
                        db_column="id_Client",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "id_Table",
                    models.ForeignKey(
                        db_column="id_Table",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.table",
                        verbose_name="Table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "db_table": "Reservation",
                "ordering": ["-Date", "Heure"],
            },
        ),
        migrations.CreateModel(
            name="Variation_Stock",
            fields=[
                ("id_Variation", models.AutoField(primary_key=True, serialize=False)),
                ("Date", models.DateField(verbose_name="Date")),
                (
                    "Type",
                    models.CharField(
                        choices=[("entrée", "Entrée"), ("sortie", "Sortie")],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "Quantite",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par",
                    ),
                ),
                (
                    "id_Ingredient",
                    models.ForeignKey(
                        db_column="id_Ingredient",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.ingredient",
                        verbose_name="Ingrédient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variation de stock",
                "verbose_name_plural": "Variations de stock",
                "db_table": "Variation_Stock",
                "ordering": ["-Date"],
            },
        ),
        migrations.CreateModel(
            name="Affectation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "Date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "id_Employe",
                    models.ForeignKey(
                        db_column="id_Employe",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.employe",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "id_Poste",
                    models.ForeignKey(
                        db_column="id_Poste",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.poste",
                        verbose_name="Poste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation",
                "verbose_name_plural": "Affectations",
                "db_table": "Affectation",
                "unique_together": {("id_Employe", "id_Poste")},
            },
        ),
        migrations.CreateModel(
            name="Ligne_Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Quantite",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "Prix_Unitaire",
                    models.IntegerField(verbose_name="Prix unitaire (FCFA)"),
                ),
                (
                    "id_Commande",
                    models.ForeignKey(
                        db_column="id_Commande",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="Restaurant.commande",
                        verbose_name="Commande",
                    ),
                ),
                (
                    "id_Produit",
                    models.ForeignKey(
                        db_column="id_Produit",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.produit",
                        verbose_name="Plat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
                "db_table": "Ligne_Commande",
                "unique_together": {("id_Commande", "id_Produit")},
            },
        ),
        migrations.CreateModel(
            name="Composition_Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Quantite_Utilisee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Quantité utilisée",
                    ),
                ),
                (
                    "id_Ingredient",
                    models.ForeignKey(
                        db_column="id_Ingredient",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.ingredient",
                        verbose_name="Ingrédient",
                    ),
                ),
                (
                    "id_Produit",
                    models.ForeignKey(
                        db_column="id_Produit",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Restaurant.produit",
                        verbose_name="Plat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composition du produit",
                "verbose_name_plural": "Compositions des produits",
                "db_table": "Composition_Produit",
                "unique_together": {("id_Produit", "id_Ingredient")},
            },
        ),
        migrations.CreateModel(
            name="Supervision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date_debut", models.DateField()),
                ("Date_fin", models.DateField(blank=True, null=True)),
                (
                    "id_Employe",
                    models.ForeignKey(
                        db_column="id_Employe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervise",
                        to="Restaurant.employe",
                        verbose_name="Employé supervisé",
                    ),
                ),
                (
                    "id_Superviseur",
                    models.ForeignKey(
                        db_column="id_Superviseur",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="superviseur",
                        to="Restaurant.employe",
                        verbose_name="Superviseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supervision",
                "verbose_name_plural": "Supervisions",
                "db_table": "Supervision",
                "unique_together": {("id_Superviseur", "id_Employe")},
            },
        ),
    ]
